<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ArenaVisualizer\ArenaVisualizer.csproj" />
    <ProjectReference Include="..\Arena\Arena.csproj" />
    <ProjectReference Include="..\DongUtility\DongUtility.csproj" />
    <ProjectReference Include="..\MotionVisualizer\MotionVisualizer.csproj" />
    <ProjectReference Include="..\VisualizerBaseClasses\VisualizerBaseClasses.csproj" />
    <ProjectReference Include="..\WPFUtility\WPFUtility.csproj" />
  </ItemGroup>

</Project>
